development:
  adapter: mysql2
  encoding: utf8
  database: rideshare_development
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: rideshare_test
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: rideshare_production
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  pool: 5
